### ISSUE TITLE
Fails in FF 58

### ISSUE THREAD

**Issue by rakeden** [pie6k/jquery.initialize#23]
Current build does not workin in FF 58.
The bug has been committed as version 1.1.0 which is not correct, since code changed. 

Have a look here and be more careful with releases please!
https://semver.org/

**Comment by dbezborodovrp** [comment]
What error are you receiving?

**Comment by rakeden** [comment]
Nevermind. fixed my project with an earlier commit of jquery.initialize

**Comment by dbezborodovrp** [comment]
@rakeden This problem was probably related to issue #25, which has been fixed in version 1.2.0.

An `npm update` to the latest version should fix the issue.
