### ISSUE TITLE
.forEach() doesn't work in old versions of chrome

### ISSUE THREAD

**Issue by jmviade** [pie6k/jquery.initialize#25]
Hello pie6k,

Recently, I update initialize() to the new version 1.1.0 that uses the function .foreach in lines 100, 102, 118 and 120. 

With new browser all is ok but old versions of chrome don't support the use of .forEach() over objects so I've got a lot of errors in console and unspected behaviours... 

I've corrected manually this issue changing .forEach with a classical structure for() and all programmes run perfectly...

the first example (for the line 100) of my 4 modifications is this next one

your code:
    mutations[m].target.parentElement.querySelectorAll(msobserver.selector).forEach(push);

my code:
   var elements = mutations[m].target.parentElement.querySelectorAll(msobserver.selector);
   for ( var i = 0; i < elements.length; i++ ) 
        push ( elements[i] );

Could you consider to introduce this little 4 changes... or perhaps ( I'm sure ) you already find a solution even better.

Thanks in advance, 

Joan Miquel

**Comment by dbezborodovrp** [comment]
Thanks for your report. We will introduce a change to use a `for` loop instead.

**Comment by dbezborodovrp** [comment]
Do you want to test the branch feature/remove-foreach? See ff6a5ca0f7709c3939dd37ac97699d68ab61f75e

**Comment by dbezborodovrp** [comment]
What version of Chrome are you using, by the way?

**Comment by jmviade** [comment]
Hi, pi6k and dbezborodovrp,

I've tested the new branch version without any problem. It seems to work perfectly. 
In those next days I'll be watching for any other inconvinience or hidden malfunction.

Tested under those two old versions
( chrome 49.0.2623.112 m ) Windows XP
( firefox 52.7.3 (32 bits) ESR ) Windows XP

Thanks. 


Joan Miquel

**Comment by dbezborodovrp** [comment]
Thanks for testing, Joan.

I have merged to `master`.

**Comment by dbezborodovrp** [comment]
This is released under 1.2.0 today. `npm update` will install the latest version.
