### ISSUE TITLE
Using a jquery selector: $('selector')

### ISSUE THREAD

**Issue by IrvingArmenta-ML** [pie6k/jquery.initialize#26]
Hello, I would like to use Jquery selectors with this plugin. This is some of the code I have right now 
```
var $labels = $(".form").not(".form--distributor").find("label");

  $.initialize($labels, function() {
    if($(this).parents('.label-auto-width').length) {
      return false;
    } else {
      $(this).css("min-width",maxWidth + "px")
    }
  });
```

It seems to work, but it throws some messages in the console

This is a warning:
```
 jQuery.Deferred exception: selector.trim is not a function TypeError: selector.trim is not a function
```

and this is an error: 
```
Uncaught TypeError: selector.trim is not a function
```

I kind a thought I could try to fix it myself, but I'm not sure about the `$.trim()` function in the `selector`.

I think jquery selectors should work without errors.

**Comment by dbezborodovrp** [comment]
Hi @IrvingArmenta-ML, the first argument to $.initialize() should be a string, not a collection. The way initialize works is to watch the DOM for new elements and mutations, instead of being passed a collection.

I suggest trying:

```
$.initialize('.form:not(.form--distributor) label', function() {
```

Good luck.
