### ISSUE TITLE
Remove initialize event

### ISSUE THREAD

**Issue by Mahmuduman** [pie6k/jquery.initialize#31]
Im Traying  a  write a bot for users download photos,when photos class was initialize the initialize event is work fine but i need sametimes deactive or remove initialize event ,
How  can i do this ?

Forexample:

$(".ImgClass").initialize( function(){
 //Codes etc...
});

I want This : 
$(".ImgClass").initialize.delete();

Its Possible  ?

**Comment by dbezborodovrp** [comment]
Initialize() returns https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver so just call disconnect() on it.

obs = $.initialize()
obs.disconnect()

**Comment by dbezborodovrp** [comment]
See also #24

**Comment by dbezborodovrp** [comment]
By the way, your code example is using the old API. See #6.
