### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by adam-jones-net** [pie6k/jquery.initialize#38]
I'm getting the following error:

> Uncaught TypeError: Cannot read property 'querySelectorAll' of null
>     at MutationObserver.<anonymous>

My implementation is fairly standard I believe...

```
$(".cart-item-price .money").initialize( function(){
	if ($(this).html().indexOf('taxes') !== -1) {
		$(this).append('<span> + taxes</span>');
	}
});
```

**Comment by eshimischi** [comment]
> I'm getting the following error:
> 
> > Uncaught TypeError: Cannot read property 'querySelectorAll' of null
> > at MutationObserver.
> 
> My implementation is fairly standard I believe...
> 
> ```
> $(".cart-item-price .money").initialize( function(){
> 	if ($(this).html().indexOf('taxes') !== -1) {
> 		$(this).append('<span> + taxes</span>');
> 	}
> });
> ```

$.initialize([selector], [callback]);

So, try $.initialize('.cart-item-price .money', function(){}); instead

**Comment by bezborodow** [comment]
This issue appears inactive and a fix was suggested. If using `$.initialize` does not resolve your issue, please reopen.
