### ISSUE TITLE
No parentElement of html

### ISSUE THREAD

**Issue by joakimriedel** [pie6k/jquery.initialize#46]
<details>
Yeah yeah I know, shouldn't use jQuery.initialize. But it's really helpful to solve refreshing the DOM in an old application I maintain that updates dynamic "time" element added using jQuery with new text.. "42 seconds ago", "41 seconds ago" etc.. Now, on to the problem.
</details>

Whenever I add an attribute to the `<html>` tag, I get `Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')` thrown on https://github.com/pie6k/jquery.initialize/blob/e21064f8c7e91dc4e706fc5f94d45d28ef19ac1e/jquery.initialize.js#L104 and https://github.com/pie6k/jquery.initialize/blob/e21064f8c7e91dc4e706fc5f94d45d28ef19ac1e/jquery.initialize.js#L121 because there is no parentElement of `<html>`.

**Comment by bezborodow** [comment]
Thank you for your report.

**Comment by bezborodow** [comment]
Fixed 1.3.2.
